project:
  type: book
  output-dir: docs
  resources: resources

execute:
  freeze: auto # re-render only changed chapters

book:
  title: Monkey Methods
  subtitle: "Welcome to the Jungle"
  author: 
    - name: Dr. Gordon Wright
      id: GW
      orcid: 0000-0001-9424-5743
      email: gordon@littlemonkeylab.com
      affiliation: 
        - name: Goldsmiths, University of London
          city: London
          state: UK
          url: www.littlemonkeylab.com
  description: "This is a an OER textbook for introductory research methods in psychology."
  date: "2023-07-09"
  doi: ""
  cover-image: images/logos/LMLLOGO.png
  image: images/logos/LMLLOGO.png
  favicon: images/logos/LMLLOGO.png
  cookie-consent: false
  license: CC BY-SA
  google-analytics: ""
  page-navigation: true
  search: true
  comments:
    hypothesis:
      theme: clean
      # openSidebar: false
  downloads: [pdf]
  sharing: []
  sidebar:
    title: "MONKEY METHODS draft"
    logo: images/logos/LMLLOGO.png
    search: true
    contents: ""
    style: floating
    background: light
    foreground: dark
    border: true
    alignment: left
    collapse-level: 3
    pinned: true
    header: ""
    footer: ""
  margin-header: ""
  page-footer:
    left: "Made by Monkeys"
    right: "With love and Quarto"
  chapters:
    - "index.qmd"
    - part: "Research Methods Text"
      chapters: 
        - "01-science-of-psych.qmd"
        - "02-getting-started.qmd"
        - "03-theory.qmd"
        - "04-ethics.qmd"
        - "05-experiments.qmd"
        - "06-measurement.qmd"
        - "07-sampling.qmd"
        - "08-complex-designs.qmd"
        - "09-nonexperiments.qmd"
        - "10-single-N.qmd"
        - "11-ideas.qmd"
        - "12-presenting.qmd"
        - "13-descriptives.qmd"
        - "14-inferentials.qmd"

   
    
  appendices:
    - webexercises.qmd



bibliography: include/book.bib
csl: include/apa.csl
citation-location: document

format:
  html:
    theme:
      light:
      - simplex
      - include/light.scss
      dark:
      - simplex
      - include/dark.scss
    css:
    - https://use.fontawesome.com/releases/v5.13.0/css/all.css
    - include/booktem.css
    - include/webex.css
    - include/glossary.css
    - include/style.css
    df-print: kable
    code-link: true
    code-fold: false
    code-line-numbers: true
    code-overflow: wrap
    code-copy: hover
    citation: true
    highlight-style: a11y
    mainfont: "Atkinson Hyperlegible"
    monofont: "Fira Code"
    include-after-body: [include/webex.js, include/script.js]
    link-citations: true
    github-repo: LittleMonkeyLab/RMText
    repo-url: https://github.com/LittleMonkeyLab/RMText
    repo-actions: [edit, issue]
  pdf:
    documentclass: scrbook
    default-image-extension: png
    keep-tex: false
    number-sections: false
    mainfont: "Atkinson Hyperlegible"
    monofont: "Fira Code"
    sansfont: "Atkinson Hyperlegible"
